version: "3.2"
services:
  react_admin:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://172.31.20.143:3006/qcloud/v1/
    ports:
      - '3005:80'
    container_name: admin_dash
